# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cb48d29c6ad27d3e91d4860d029f917c5d3bb22fb25f9c63e049f7b4319382fa9b54f367d37db7bfd9ebd82b5e0dccc9e8ba18ee81935a9505e22e9975e64d0

test:
  secret_key_base: 5bc96a67575fc908c204a55f49405552bf866ade01cd8e5deb10c3f495c44f5ff3bbaf80479d462b98cf0a20de9a9e663269a7dde56b6317800e9bda909f951b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
